### ISSUE TITLE
Themes parser broken

### ISSUE THREAD

**Issue by moreginger** [moreginger/xbmc-plugin.video.ted.talks#53]
Reported [here](http://forum.kodi.tv/showthread.php?tid=36866&pid=1932334#pid1932334)

```
14:48:13 T:4556  NOTICE: [PLUGIN] Initialized TED Talks v4.2.4 using Python: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]'
14:48:14 T:4556  NOTICE: [TED Talks] resources.lib.model.fetcher attempting to open http://www.ted.com/themes with data
14:48:14 T:4556   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Dave\AppData\Roaming\Kodi\addons\plugin.video.ted.talks\default.py", line 17, in <module>
                                                ted_talks.Main(args_map=args_map).run()
                                              File "C:\Users\Dave\AppData\Roaming\Kodi\addons\plugin.video.ted.talks\resources\lib\ted_talks.py", line 326, in run
                                                modes[mode].run(self.args_map)
                                              File "C:\Users\Dave\AppData\Roaming\Kodi\addons\plugin.video.ted.talks\resources\lib\ted_talks.py", line 147, in run
                                                self.run_internal(args)
                                              File "C:\Users\Dave\AppData\Roaming\Kodi\addons\plugin.video.ted.talks\resources\lib\ted_talks.py", line 237, in run_internal
                                                self.ui.themes()
                                              File "C:\Users\Dave\AppData\Roaming\Kodi\addons\plugin.video.ted.talks\resources\lib\ted_talks.py", line 122, in themes
                                                for title, link, img, count in themes.get_themes():
                                              File "C:\Users\Dave\AppData\Roaming\Kodi\addons\plugin.video.ted.talks\resources\lib\model\themes_scraper.py", line 12, in get_themes
                                                themes_div = xbmc_common.parseDOM(html, 'div', {'class':'box themes'})[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
14:48:14 T:5968   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ted.talks/?mode=themes
14:48:14 T:5968   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ted.talks/?mode=themes) failed
```

**Comment by moreginger** [comment]
Looks like Themes are no more and have been replaced by topics. Luckily topics category already contributed in #52.
