### ISSUE TITLE
Failed to Load with Raspbian

### ISSUE THREAD

**Issue by albanlorillard** [moreginger/xbmc-plugin.video.ted.talks#56]
Hi ! ( Firstly, i'm french, and i'm sorry for my rought english ;) )
I just to install my RaspBerry Pi 2 with Kodi but after installing the Ted Talk's plugin, when i choose and load a video, i have this error : 

```
18:37:21 T:1587540912  NOTICE: Thread LanguageInvoker start, auto delete: false
18:37:21 T:1587540912  NOTICE: -->Python Interpreter Initialized<--
18:37:21 T:1587540912  NOTICE: CommonFunctions-2.5.1
18:37:21 T:1587540912  NOTICE: [PLUGIN] Initialized TED Talks v4.2.6 using Python: 2.7.9 (default, Mar  8 2015, 01:22:25) 
                                            [GCC 4.9.2]'
18:37:21 T:1587540912  NOTICE: [TED Talks] resources.lib.model.fetcher attempting to open http://feedproxy.google.com/~r/TEDTalks_video/~3/6adaAJ3arU4/oscar_schwartz_can_a_computer_write_poetry with data
18:37:24 T:1658823600   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
18:37:32 T:1587540912   ERROR: exceptions
18:37:32 T:1587540912   ERROR: Previous line repeats 1 times.
18:37:32 T:1587540912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: string index out of range
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.ted.talks/default.py", line 17, in <module>
                                                ted_talks.Main(args_map=args_map).run()
                                              File "/root/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 318, in run
                                                modes[mode].run(self.args_map)
                                              File "/root/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 134, in run
                                                self.run_internal(args)
                                              File "/root/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 152, in run_internal
                                                self.ui.playVideo(args['url'], args['icon'] if 'icon' in args else None)
                                              File "/root/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 71, in playVideo
                                                title, url, subs, info_labels = self.ted_talks.getVideoDetails(url=url, video_quality=settings.video_quality, subs_language=subs_language)
                                              File "/root/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 17, in getVideoDetails
                                                video_url, title, speaker, plot, talk_json = talk_scraper.get(talk_html, video_quality)
                                              File "/root/.kodi/addons/plugin.video.ted.talks/resources/lib/model/talk_scraper.py", line 47, in get
                                                headline = xbmc_common.parseDOM(html, 'span', attrs={'id':'altHeadline'})[0].split(':', 1)
                                            IndexError: string index out of range
                                            -->End of Python script error report<--
18:37:32 T:1947136000   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ted.talks/?url=http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2FTEDTalks_video%2F%7E3%2F6adaAJ3arU4%2Foscar_schwartz_can_a_computer_write_poetry&mode=playVideo&icon=http%3A%2F%2Ftedcdnpe-a.akamaihd.net%2Fimages%2Fted%2Fdd088ee80b3c3ec5dd53ee78b75ec3c32a74a24e_389x292.jpg]
```

Kodi 15.2 (Compiled Dec 28 2015) / Last RaspBian Jessie (Kernel: 4.1.13-v7+)

**Comment by moreginger** [comment]
That's odd. It's working for me (not on rPi). It looks like something went wrong upstream and it failed to parse the page html correctly. Is there any chance that the problem has fixed itself? Is it the same for all talks?

**Comment by moreginger** [comment]
Assumed no longer a problem.
