### ISSUE TITLE
Can't play video

### ISSUE THREAD

**Issue by wilfriedroset** [moreginger/xbmc-plugin.video.ted.talks#66]
On a rpi3 running libreelec 8.0.1 with ted plugin 4.2.10 I'm unable to watch a video. Here's is the content of the log. This start happening last week.

```
17:48:18.633 T:1690301344  NOTICE: [PLUGIN] Initialized TED Talks v4.2.10 using Python: 2.7.13 (default, Mar  2 2017, 11:37:04)
                                            [GCC 6.2.0]'
17:48:18.758 T:1690301344  NOTICE: [TED Talks] resources.lib.model.fetcher attempting to open http://feedproxy.google.com/~r/TEDTalks_video/~3/bZi-EIqQqzg/maurice_conti_the_incredible_inventions_of_intuitive_ai with data
17:48:18.763 T:1690301344  NOTICE: [TED Talks] loaded cookie : <Cookie _abby=2jYFkpwTnNH3WOs for .ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
17:48:18.763 T:1690301344  NOTICE: [TED Talks] loaded cookie : <Cookie _abby_aa_forever=a for www.ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
17:48:18.763 T:1690301344  NOTICE: [TED Talks] loaded cookie : <Cookie _abby_hydro_hog=c for www.ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
17:48:18.763 T:1690301344  NOTICE: [TED Talks] loaded cookie : <Cookie _nu=1491493475.993 for www.ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
17:48:20.047 T:1690301344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: "talks\nfor url 'http://feedproxy.google.com/~r/TEDTalks_video/~3/bZi-EIqQqzg/maurice_conti_the_incredible_inventions_of_intuitive_ai'"
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/default.py", line 17, in <module>
                                                ted_talks.Main(args_map=args_map).run()
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 322, in run
                                                modes[mode].run(self.args_map)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 134, in run
                                                self.run_internal(args)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 152, in run_internal
                                                self.ui.playVideo(args['url'], args['icon'] if 'icon' in args else None)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 69, in playVideo
                                                title, url, subs, info_labels = self.ted_talks.getVideoDetails(url=url, video_quality=settings.video_quality, subs_language=subs_language)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 20, in getVideoDetails
                                                raise type(e)(e.message + "\nfor url '%s'" % (url))
                                            KeyError: "talks\nfor url 'http://feedproxy.google.com/~r/TEDTalks_video/~3/bZi-EIqQqzg/maurice_conti_the_incredible_inventions_of_intuitive_ai'"
                                            -->End of Python script error report<--
17:48:20.172 T:1961950160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ted.talks/?url=http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2FTEDTalks_video%2F%7E3%2FbZi-EIqQqzg%2Fmaurice_conti_the_incredible_inventions_of_intuitive_ai&mode=playVideo&icon=https%3A%2F%2Fpi.tedcdn.com%2Fr%2Fpe.tedcdn.com%2Fimages%2Fted%2F230aaccbc41c53f9225a0e86fb4ae3ad7578f595_389x292.jpg%3Fh%3D360%26origin%3Drss%26w%3D480]
```

**Comment by rockclimb** [comment]
I'm seeing the same - it looks like TED have updated the page - see the announcement at http://blog.ted.com/an-updated-design-for-ted-talks/

**Comment by rockclimb** [comment]
This patch seems to mostly fix the problem:
```
diff --git a/resources/lib/model/talk_scraper.py b/resources/lib/model/talk_scraper.py
index 8ecdada..37dc8c0 100644
--- a/resources/lib/model/talk_scraper.py
+++ b/resources/lib/model/talk_scraper.py
@@ -15,13 +15,13 @@ def get(html, video_quality='320kbps'):
     init_scripts = [script for script in xbmc_common.parseDOM(html, 'script') if '"talkPage.init"' in script]
     if init_scripts:
         init_json = json.loads(re.compile(r'q[(]"talkPage.init",(.+)[)]').search(init_scripts[0]).group(1))
-        talk_json = init_json['talks'][0]
+        talk_json = init_json[u'__INITIAL_DATA__']['talks'][0][u'player_talks'][0]
         title = talk_json['title']
         speaker = talk_json['speaker']
 
         if talk_json['resources']['h264']:
             url = talk_json['resources']['h264'][0]['file']
-            plot = xbmc_common.parseDOM(html, 'p', attrs={'class':'talk-description'})[0]
+            plot = init_json[u'__INITIAL_DATA__']['description']
 
             if not video_quality == '320kbps':
                 url_custom = url.replace("-320k.mp4", "-%sk.mp4" % (video_quality.split('k')[0]))
```

**Comment by wilfriedroset** [comment]
I do not witness this issue lately. I'm closing this. Thanks.
