### ISSUE TITLE
Plugin fails to play any video

### ISSUE THREAD

**Issue by vasyugan** [moreginger/xbmc-plugin.video.ted.talks#69]
With latest libreelec:
```
13:08:14.735 T:1363088288  NOTICE: [TED Talks] resources.lib.model.fetcher attempting to open http://feedproxy.google.com/~r/TEDTalks_video/~3/zQcQUl5EReM/justin_davidson_why_shiny_glass_towers_are_bad_for_city_life with data
13:08:14.752 T:1363088288  NOTICE: [TED Talks] loaded cookie : <Cookie _abby=B3Dy2shaQYilj36 for .ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
13:08:14.753 T:1363088288  NOTICE: [TED Talks] loaded cookie : <Cookie _abby_choobo=a for www.ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
13:08:14.753 T:1363088288  NOTICE: [TED Talks] loaded cookie : <Cookie _abby_sir_search_alot=a for www.ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
13:08:14.753 T:1363088288  NOTICE: [TED Talks] loaded cookie : <Cookie _nu=1487277556.684 for www.ted.com/> from /storage/.kodi/temp/ted-cookies.lwp
13:08:15.024 T:1786770336   ERROR: EXCEPTION: Unknown addon id 'skin.unity'.
13:08:15.026 T:1786770336 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.service/resources/lib/main_service.py", line 74, in check_skin_version
                                                skin_addon = xbmcaddon.Addon(id=skin)
                                            RuntimeError: Unknown addon id 'skin.unity'.
13:08:15.026 T:1786770336   ERROR: Skin Helper Service --> Exception in resources.lib.main_service ! --> Unknown addon id 'skin.unity'.
13:08:15.817 T:1363088288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            for url 'http://feedproxy.google.com/~r/TEDTalks_video/~3/zQcQUl5EReM/justin_davidson_why_shiny_glass_towers_are_bad_for_city_life'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/default.py", line 23, in <module>
                                                ted_talks.Main(args_map=args_map).run()
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 332, in run
                                                modes[mode].run(self.args_map)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 144, in run
                                                self.run_internal(args)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 162, in run_internal
                                                self.ui.playVideo(args['url'], args['icon'] if 'icon' in args else None)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 79, in playVideo
                                                title, url, subs, info_labels = self.ted_talks.getVideoDetails(url=url, video_quality=settings.video_quality, subs_language=subs_language)
                                              File "/storage/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 20, in getVideoDetails
                                                raise type(e)(e.message + "\nfor url '%s'" % (url))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            for url 'http://feedproxy.google.com/~r/TEDTalks_video/~3/zQcQUl5EReM/justin_davidson_why_shiny_glass_towers_are_bad_for_city_life'
                                            -->End of Python script error report<--
13:08:16.021 T:1962146912   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ted.talks/?url=http%3A%2F%2Ffeedproxy.google.com%2F%7Er%2FTEDTalks_video%2F%7E3%2FzQcQUl5EReM%2Fjustin_davidson_why_shiny_glass_
towers_are_bad_for_city_life&mode=playVideo]
```

**Comment by moreginger** [comment]
Hi, I'm trying to get 4.2.12 pulled in. Hopefully that will fix it?

https://github.com/xbmc/repo-plugins/pull/1319
